namespace LLMeta.App.Models;

public readonly record struct OpenXrControllerState(
    bool IsInitialized,
    string Status,
    OpenXrHeadPoseState HeadPose,
    float IpdMeters,
    float HmdVerticalFovDegrees,
    float LeftEyeAngleLeftRadians,
    float LeftEyeAngleRightRadians,
    float LeftEyeAngleUpRadians,
    float LeftEyeAngleDownRadians,
    float RightEyeAngleLeftRadians,
    float RightEyeAngleRightRadians,
    float RightEyeAngleUpRadians,
    float RightEyeAngleDownRadians,
    float LeftStickX,
    float LeftStickY,
    float RightStickX,
    float RightStickY,
    float LeftTriggerValue,
    float LeftGripValue,
    float RightTriggerValue,
    float RightGripValue,
    bool LeftStickClickPressed,
    bool RightStickClickPressed,
    bool LeftXPressed,
    bool LeftYPressed,
    bool RightAPressed,
    bool RightBPressed
);
